---
jobs:  
- name: build-test-image
  public: true
  serial: true
  plan:
  - get: stackdriver-tools-src-in
    trigger: true
  - put: docker-image-test
    params:
      build: stackdriver-tools-src-in/ci/docker-image

- name: verify-test-image
  public: true
  serial: true
  plan:
  - {trigger: true, passed: [build-test-image], get: stackdriver-tools-src-in}
  - task: verify-test-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_hub_test_repo}}
      inputs:
      - name: stackdriver-tools-src-in
      run:
        path: stackdriver-tools-src-in/ci/docker-image/tasks/verify-test-image.sh


- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: stackdriver-tools-src-in
    trigger: true
    passed: [verify-test-image]
  - put: docker-image
    params:
      build: stackdriver-tools-src-in/ci/docker-image

resources:  
  - name: stackdriver-tools-src-in
    type: git
    source: 
      uri:      {{source_uri}}
      branch:   {{source_branch}}
      paths:    [ci/docker-image]

  - name: docker-image-test
    type: docker-image
    source:
      email: {{docker_hub_email}}
      username: {{docker_hub_username}}
      password: {{docker_hub_password}}
      repository: {{docker_hub_test_repo}}

  - name: docker-image
    type: docker-image
    source:
      email: {{docker_hub_email}}
      username: {{docker_hub_username}}
      password: {{docker_hub_password}}
      repository: {{docker_hub_repo}}
