---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfplatformeng/tile-generator

inputs:
  - name: stackdriver-tools

run:
  dir: stackdriver-tools
  path: sh
  args: [-c, "apk add --no-cache make && make bosh-release"]
