---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: jrjohnsongoog/stackdriver-tools-ci
inputs:
  - name: stackdriver-tools
  - name: version-semver
outputs:
  - name: candidate
run:
  path: stackdriver-tools/ci/tasks/build-candidate.sh
params:
  service_account_key_json: replace-me