---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: lambr/gcp-tools
    tag: v1
inputs:
  - name: gcp-tools-release
  - name: version-semver
outputs:
  - name: candidate
run:
  path: gcp-tools-release/ci/tasks/build-candidate.sh
