---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: lambr/gcp-tools
    tag: v3
inputs:
  - name: stackdriver-tools
  - name: version-semver
outputs:
  - name: candidate

run:
  path: stackdriver-tools/ci/tasks/build-tile.sh
