---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfplatformeng/tile-generator 
inputs:
  - name: stackdriver-tools
  - name: version-semver
outputs:
  - name: candidate

run:
  path: stackdriver-tools/ci/tasks/build-tile.sh
