---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfplatformeng/tile-generator
    tag: v11.0.5
inputs:
  - name: stackdriver-tools
  - name: stackdriver-tools-artifacts
  - name: version-semver
outputs:
  - name: candidate
params:
  tile_name: replace-me
  tile_label: replace-me

run:
  path: stackdriver-tools/ci/tasks/build-tile.sh
