---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: stackdriver-tools

run:
  dir: stackdriver-tools
  path: ./ci/setup-gopath.sh
  args: [make, get-deps, lint]
