---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
    tag: v2
inputs:
  - name: gcp-tools-release
outputs:
  - name: candidate
run:
  path: gcp-tools-release/ci/tasks/unit-tests.sh
