---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: jrjohnsongoog/stackdriver-tools-ci
inputs:
  - name: stackdriver-tools
run:
  path: stackdriver-tools/ci/tasks/unit-tests.sh
