---
name: stackdriver-nozzle

releases:
- name: stackdriver-tools
  version: latest

# This block does not belong in here or needs to be specialized for GCP in a different way
stemcells:
- alias: default
  name: bosh-google-kvm-ubuntu-xenial-go_agent
  version: latest

instance_groups:
- name: stackdriver-nozzle
  instances: 1
  networks:
  - name: default
  azs: [z1]
  vm_type: default
  persistent_disk_type: default
  stemcell: default
  jobs:
  - name: stackdriver-nozzle
    release: stackdriver-tools
    consumes:
      reverse_log_proxy:
        from: reverse_log_proxy
        deployment: cf
  - name: google-fluentd
    release: stackdriver-tools
  - name: stackdriver-agent
    release: stackdriver-tools
  properties:
    rlp:
      ca_cert: ((loggregator_ca.ca))
      cert: ((stackdriver_nozzle.certificate))
      key: ((stackdriver_nozzle.private_key))
    firehose:
      endpoint: ((firehose_endpoint))
      username: ((firehose_username))
      password: ((firehose_password))
      skip_ssl: ((skip_ssl))
      events_to_stackdriver_logging: LogMessage,Error,HttpStartStop
      events_to_stackdriver_monitoring: CounterEvent,ValueMetric,ContainerMetric
    gcp:
      project_id: ((gcp_project_id))
    credentials:
      application_default_credentials: ((gcp_service_account_json))

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
  - name: stackdriver_nozzle
    type: certificate
    options:
      ca: loggregator_ca
      common_name: stackdriver-nozzle
      extended_key_usage:
        - client_auth
        - server_auth