---
jobs:
  - name: test-unit
    plan:
      - aggregate:
        - {trigger: true,  get: stackdriver-tools,   resource: stackdriver-tools-in}

      - task: unit-tests
        file: stackdriver-tools/ci/tasks/unit-tests.yml
        on_failure:
          aggregate:
            - put: slack-alert
              params:
                icon_emoji: ":robot_face:"
                username: Build pipeline
                channel: "#lambr-private"
                text: "unit-tests failed"


  - name: build-candidate
    plan:
      - aggregate:
        - {trigger: true, passed: [test-unit],  get: stackdriver-tools,   resource: stackdriver-tools-in}
        - {trigger: false, get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: make-semver-public
        file: stackdriver-tools/ci/tasks/public-semver.yml
        params:
          project_id: {{project_id}}
          bucket_name: {{bucket_name}}
          semver_key: beta/stackdriver-tools/current-version

      - task: build-release
        file: stackdriver-tools/ci/tasks/build-candidate.yml
        on_failure:
          aggregate:
            - put: slack-alert
              params:
                icon_emoji: ":robot_face:"
                username: Build pipeline
                channel: "#lambr-private"
                text: "build-release failed"

      - put: stackdriver-tools-artifacts
        params: {file: candidate/*.tgz}

      - put: stackdriver-tools-artifacts-sha256
        params: {file: candidate/*.tgz.sha256}

  - name: build-tile
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],   get: stackdriver-tools,                resource: stackdriver-tools-in}
        - {trigger: true,  passed: [build-candidate],   get: stackdriver-tools-artifacts,      resource: stackdriver-tools-artifacts}
        - {trigger: false,                              get: version-semver,                   resource: version-semver}

      - task: build-tile
        file: stackdriver-tools/ci/tasks/build-tile.yml
        params:
          tile_name: stackdriver-nozzle
          tile_label: Stackdriver Nozzle
        on_failure:
          aggregate:
            - put: slack-alert
              params:
                icon_emoji: ":robot_face:"
                username: Build pipeline
                channel: "#lambr-private"
                text: "build-tile failed"

      - put: stackdriver-nozzle-tile
        params: {file: candidate/*.pivotal}

      - put: stackdriver-nozzle-tile-sha256
        params: {file: candidate/*.pivotal.sha256}

  - name: deploy-candidate
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: stackdriver-tools,                resource: stackdriver-tools-in}
        - {trigger: true,  passed: [build-candidate],  get: stackdriver-tools-artifacts,      resource: stackdriver-tools-artifacts}
        - {trigger: false, passed: [build-candidate],  get: stackdriver-tools-artifacts-sha256, resource: stackdriver-tools-artifacts-sha256}
        - {trigger: false,                             get: version-semver,                   resource: version-semver}

      - task: deploy-candidate
        file: stackdriver-tools/ci/tasks/deploy-candidate.yml
        attempts: 2
        on_failure:
          aggregate:
            - put: slack-alert
              params:
                icon_emoji: ":robot_face:"
                username: Build pipeline
                channel: "#lambr-private"
                text: "deploy-candidate failed"
        params:
          ssh_bastion_address: {{ssh_bastion_address}}
          ssh_user: {{ssh_user}}
          ssh_key: {{ssh_key}}
          bosh_director_address: {{bosh_director_address}}
          bosh_user: {{bosh_user}}
          bosh_password: {{bosh_password}}
          google_region: {{google_region}}
          google_zone: {{google_zone}}
          network: {{network}}
          public_subnetwork: {{public_subnetwork}}
          private_subnetwork: {{private_subnetwork}}
          cf_project_id: {{cf_project_id}}
          cf_service_account: {{cf_service_account}}
          firehose_username: {{firehose_username}}
          firehose_password: {{firehose_password}}
          cf_api_url: {{cf_api_url}}
          service_account_key_json: {{service_account_key_json}}
          cf_service_account_json: {{cf_service_account_json}}

  - name: promote-candidate 
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-tile],        get: stackdriver-nozzle-tile,          resource: stackdriver-nozzle-tile}
        - {trigger: true,  passed: [deploy-candidate],  get: stackdriver-tools,                resource: stackdriver-tools-in}
        - {trigger: true,  passed: [deploy-candidate],  get: stackdriver-tools-artifacts,      resource: stackdriver-tools-artifacts}
        - {trigger: false, passed: [deploy-candidate],  get: stackdriver-tools-artifacts-sha256, resource: stackdriver-tools-artifacts-sha256}

      - task: promote-candidate
        file: stackdriver-tools/ci/tasks/promote-candidate.yml
        attempts: 2
        on_failure:
          aggregate:
            - put: slack-alert
              params:
                icon_emoji: ":robot_face:"
                username: Build pipeline
                channel: "#lambr-private"
                text: "promote-candidate failed"

      - put: stackdriver-tools-artifacts
        params: {file: candidate/latest.tgz}

      - put: stackdriver-tools-artifacts-sha256
        params: {file: candidate/latest.tgz.sha256}

      - put: stackdriver-nozzle-tile
        params: {file: candidate/latest.pivotal}

resources:
  - name: stackdriver-tools-in
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/stackdriver-tools.git
      branch: master
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: stackdriver-tools-artifacts
    type: gcs-resource
    source:
      json_key: {{service_account_key_json}}
      bucket:   {{bucket_name}}
      regexp:   beta/stackdriver-tools/stackdriver-tools([0-9]+\.[0-9]+\.[0-9]+)\.tgz

  - name: stackdriver-tools-artifacts-sha256
    type: gcs-resource
    source:
      json_key: {{service_account_key_json}}
      bucket:   {{bucket_name}}
      regexp:   beta/stackdriver-tools/stackdriver-tools([0-9]+\.[0-9]+\.[0-9]+)\.tgz.sha256

  - name: stackdriver-nozzle-tile
    type: gcs-resource
    source:
      json_key: {{service_account_key_json}}
      bucket:   {{bucket_name}}
      regexp:   beta/stackdriver-tools/stackdriver-nozzle-tile([0-9]+\.[0-9]+\.[0-9]+)\.pivotal

  - name: stackdriver-nozzle-tile-sha256
    type: gcs-resource
    source:
      json_key: {{service_account_key_json}}
      bucket:   {{bucket_name}}
      regexp:   beta/stackdriver-tools/stackdriver-nozzle-tile([0-9]+\.[0-9]+\.[0-9]+)\.pivotal.sha256

  - name: version-semver
    type: semver
    source:
      key:               beta/stackdriver-tools/current-version
      bucket:            {{bucket_name}}
      access_key_id:     {{bucket_access_key}}
      secret_access_key: {{bucket_secret_key}}
      region:            US
      endpoint:          storage.googleapis.com

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-hook}}


resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
