---
jobs:
  - name: lint
    plan:
      - get: stackdriver-tools
        trigger: true
      - task: test
        file: stackdriver-tools/ci/tasks/lint.yml
  - name: build
    plan:
      - get: stackdriver-tools
        trigger: true
      - task: test
        file: stackdriver-tools/ci/tasks/build.yml
  - name: test
    plan:
      - get: stackdriver-tools
        trigger: true
      - task: test
        file: stackdriver-tools/ci/tasks/test.yml
  - name: bosh-release
    plan:
      - get: stackdriver-tools
        trigger: true
        passed: [lint, build, test]
      - task: test
        file: stackdriver-tools/ci/tasks/bosh-release.yml
  - name: tile
    plan:
      - get: stackdriver-tools
        trigger: true
        passed: [lint, build, test]
      - task: test
        file: stackdriver-tools/ci/tasks/tile.yml

resources:
  - name: stackdriver-tools
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/stackdriver-tools.git
      branch: update-ci
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml
