---
groups:
  - name: gcp-tools-release
    jobs:
      - test-unit
      - build-candidate

jobs:
  - name: test-unit
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  get: gcp-tools-release,   resource: gcp-tools-release-in}

      - task: unit-tests
        file: gcp-tools-release/ci/tasks/unit-tests.yml

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: true, passed: [test-unit],  get: gcp-tools-release,   resource: gcp-tools-release-in}
        - {trigger: false, get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build-release
        file: gcp-tools-release/ci/tasks/build-candidate.yml

      - put: gcp-tools-release-artifacts
        params: {file: candidate/*.tgz}

      - put: gcp-tools-release-artifacts-sha1
        params: {file: candidate/*.tgz.sha1}

resources:
  - name: gcp-tools-release-in
    type: git
    source:
      uri: https://github.com/evandbrown/gcp-tools-release.git
      branch: develop
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: gcp-tools-release-artifacts
    type: gcs-resource
    source:
      json_key: {{service_account_key_json}}
      bucket:   {{bucket_name}}
      regexp:   gcp-tools-release([0-9]+\.[0-9]+\.[0-9]+)\.tgz

  - name: gcp-tools-release-artifacts-sha1
    type: gcs-resource
    source:
      json_key: {{service_account_key_json}}
      bucket:   {{bucket_name}}
      regexp:   gcp-tools-release([0-9]+\.[0-9]+\.[0-9]+)\.tgz.sha1

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{bucket_name}}
      access_key_id:     {{bucket_access_key}}
      secret_access_key: {{bucket_secret_key}}
      region:            US
      endpoint:          storage.googleapis.com

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
